# default profile for RTT

[default.general]
chip = "STM32F103C8"

[default.rtt]
enabled = true

# debug profile for gdb

[debug.reset]
halt_afterwards = true

[debug.rtt]
enabled = false

[debug.gdb]
enabled = true
